# Generated by Django 3.1.7 on 2021-04-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('orgname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('numb_of_ppl', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('sector', models.CharField(max_length=100)),
            ],
        ),
    ]
