# Generated by Django 3.1.7 on 2021-04-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_yearly_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.AutoField(primary_key=True, serialize=False)),
                ('personname', models.CharField(max_length=100)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10)),
                ('age', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
    ]
