# Generated by Django 3.1.7 on 2021-04-13 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_org',
            field=models.ForeignKey(default='Other', on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(default='Other', on_delete=django.db.models.deletion.CASCADE, to='core.person'),
        ),
    ]
